version: '3.8'

services:
  app:
    image: wfelipe2011/notifly:master
    ports:
      - '${NOTIFLY_PORT}:${NOTIFLY_PORT}'
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - WHATSAPP_USERNAME=${WHATSAPP_USERNAME}
      - WHATSAPP_PASSWORD=${WHATSAPP_PASSWORD}
      - NOTIFLY_PORT=${NOTIFLY_PORT}
      - JWT_SECRET=${JWT_SECRET}
      - WHATSAPP_TOKEN=${WHATSAPP_TOKEN}
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.2"
          memory: 256M
