version: '3.8'

services:
  app:
    image: wfelipe2011/captura:master
    ports:
      - '8000:8000'
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - WHATSAPP_USERNAME=${WHATSAPP_USERNAME}
      - WHATSAPP_PASSWORD=${WHATSAPP_PASSWORD}
      - PORT=7000
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
