version: '3.8'

services:
  app:
    # image: wfelipe2011/captura:master
    build: 
      context: .
      dockerfile: Dockerfile.captura
    ports:
      - '8000:8000'
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - WHATSAPP_USERNAME=${WHATSAPP_USERNAME}
      - WHATSAPP_PASSWORD=${WHATSAPP_PASSWORD}
      - PORT=8000
    restart: always # Essa opção reinicia o container automaticamente se ele falhar
    
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 1024M