version: '3.8'

services:
  app:
    image: wfelipe2011/gym:master
    ports:
      - '8010:8010'
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - WHATSAPP_USERNAME=${WHATSAPP_USERNAME}
      - WHATSAPP_PASSWORD=${WHATSAPP_PASSWORD}
      - GYM_PORT=8010
      - JWT_SECRET=${JWT_SECRET}
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.2"
          memory: 256M
